export const HOME_SET_YIKATONG_SCENICS = 'HOME_SET_YIKATONG_SCENICS'
export const HOME_SET_YIKATONG_AREAS = 'HOME_SET_YIKATONG_AREAS'
export const HOME_SET_FILTERING_STATE = 'HOME_SET_FILTERING_STATE'
export const HOME_SET_FILTERED_SCENICS = 'HOME_SET_FILTERED_SCENICS'